name: ci

on:
  pull_request:
    branches:
    - '**'

jobs:
  lint_test:
    uses: babylonchain/.github/.github/workflows/reusable_go_lint_test.yml@v0.1.0
    with:
     run-unit-tests: true
     run-lint: true